# Generated by Django 5.1.1 on 2024-09-23 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triptuner", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Itinerary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="ItineraryDestination",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("visit_order", models.PositiveIntegerField()),
                ("destination", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="triptuner.destination")),
                ("itinerary", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="triptuner.itinerary")),
            ],
            options={
                "ordering": ["visit_order"],
            },
        ),
        migrations.AddField(
            model_name="itinerary",
            name="destinations",
            field=models.ManyToManyField(
                related_name="itineraries", through="triptuner.ItineraryDestination", to="triptuner.destination"
            ),
        ),
    ]
